<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>Campanion.Shared</PackageId>
    <Title>Campanion Shared Library</Title>
    <Version>1.1.13</Version>
    <Description>Shared library to connect the MAUI frontend with the the ASP .NET Core API on the backend. Will not serve any other purpose than developing the Campanion native mobile application.</Description>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Dtos\CampgroundDtos\" />
  </ItemGroup>

</Project>
